# -*- coding: utf-8 -*-
"""TP4_Mairene-Villasmil

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b5ncWOCxX6ybi0JsycPhkmOCACUSYbX_

# Realizar un analisis de grafico de chernoff y detectar outlires

# **DATASET TITANIC**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#titanic
df = pd.read_csv('https://raw.githubusercontent.com/mrBronnWow/Curso_Beginners/main/1_Dataset_titanic/train.csv')
print(df.head())
#iris
url = 'https://raw.githubusercontent.com/mrBronnWow/Curso_Beginners/main/1_Dataset_titanic/train.csv'
#url_iris = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
#dataset_iris=pd.read_csv(url_iris)
#print(dataset_iris)
df = pd.read_csv(url)

#TIPOS DE VARIABLES

variables = df.columns.tolist()#columnas como lista
print("Variables en el dataset:")
for variable in variables:
    print(variable)

print('\n')

#Valores Ausente
tipos_de_datos = df.dtypes #muestra los tipos de datos
print("Tipos de Categorías de Variables:")
print(tipos_de_datos)

print('\n')

#Valores Ausente
print("------------CANTIDAD DE DATOS NULOS---------------")
cantidad_de_datos_nulos_= df.isnull().sum() #contamos la cantidad de datos None
print(cantidad_de_datos_nulos_)


#Valor Atipico
#para ver el valor atipico vamos a obtener los datos del dataset
valor_atipico = df.describe()
#print(valor_atipico)
#Analizar----------------------------------------------------------------

#En esta lista de Variables estan TODAS y su eexplicacion con referencia al
#dataset y el tipo de variable que seria

# Variables en el dataset y su explicación
variables_explicacion = {
    'Survived': 'Sobrevivio (0 = No, 1 = Sí)',
    'Pclass': 'Clase de pasajero (1 = Primera, 2 = Segunda, 3 = Tercera)',
    'Name': 'Nombre del pasajero',
    'Sex': 'Género del pasajero',
    'Age': 'Edad del pasajero',
    'SibSp': 'Número de hermanos/cónyuges a bordo',
    'Parch': 'Número de padres/hijos a bordo',
    'Ticket': 'Número de ticket',
    'Fare': 'Tarifa del pasajero',
    'Cabin': 'Número de camarote',
    'Embarked': 'Puerto de embarque (C = Cherbourg, Q = Queenstown, S = Southampton)'
}

# Tipos de Categorías de Variables
categorias_variable = {
    'Survived': 'Categórica (Nominal)',
    'Pclass': 'Categórica (Ordinal)',
    'Name': 'Categórica (Nominal)',
    'Sex': 'Categórica (Nominal)',
    'Age': 'Numérica (Continua)',
    'SibSp': 'Numérica (Discreta)',
    'Parch': 'Numérica (Discreta)',
    'Ticket': 'Categórica (Nominal)',
    'Fare': 'Numérica (Continua)',
    'Cabin': 'Categórica (Nominal)',
    'Embarked': 'Categórica (Nominal)'
}

# Imprimir información de variables y categorías
for variable, explicacion in variables_explicacion.items():
    categoria = categorias_variable[variable]
    print(f'Variable: {variable}')
    print(f'Explicación: {explicacion}')
    print(f'Categoría: {categoria}')
    print('-----------------------------------')
print('--------------------termino---------------------')




url_titanic = 'https://raw.githubusercontent.com/mrBronnWow/Curso_Beginners/main/1_Dataset_titanic/train.csv'
df_titanic = pd.read_csv(url_titanic)
print(df_titanic)

#verifico datos faltantes dataset
print('datos faltantes: ')
print(pd.isnull(df_titanic).sum())

#verifico las estadisticas
print('Estadisticas:')
print(df_titanic.describe())


#Elimino la columna SibSp
titanic_eliminado = df_titanic.drop(['SibSp'], axis=1)
print(titanic_eliminado)




# Gráfico de Frecuencia
plt.figure(figsize=(8, 6))
sns.countplot(x='Pclass', data=df_titanic)
plt.title('Gráfico de Frecuencia de Clase de Pasajero')
plt.show()


# Gráfico de Torta
plt.figure(figsize=(8, 6))
df_titanic['Survived'].value_counts().plot.pie(autopct='%1.1f%%')
plt.title('Gráfico de Torta de Sobrevivientes')
plt.show()


# Histograma
plt.figure(figsize=(8, 6))
df_titanic['Age'].plot.hist(bins=20, edgecolor='black')
plt.title('Histograma de Edades')
plt.xlabel('Edad')
plt.ylabel('Frecuencia')
plt.show()

# **En base a los graficos del punto 6 realizar distintas concluciones**

#*La mayor cantidad de pasajeros viajaba en la clase mas económica del barco.

#*El porcentaje de sobrevivientes fue menor con respecto al total de muertes, siendo menos del 50% de las personas a bordo.

#*El rango de edades donde se encontro mayor cantidad de pasajeros fue entre los 20 y 20 años.





# Lista de columnas numéricas
columnas_numericas = ['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

# Calcular la matriz de correlación
correlation_matrix = df_titanic[columnas_numericas].corr()

# Crear el gráfico de calor
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Matriz de Correlación')
plt.show()

# Los colores más claros (cercanos a 1) indican una correlación positiva fuerte.
# Los colores más oscuros (cercanos a -1) indican una correlación negativa fuerte.
# Los colores neutros (cercanos a 0) indican una correlación débil o nula.

# **ANALISIS DEL GRAFICO DE CORRELACION**

#Supongamos que se observa una celda en el gráfico que es de color claro y cercana a 1 en la intersección de las variables 'Survived' y 'Fare'. Esto indica que hay una correlación positiva entre la tarifa pagada (Fare) y la supervivencia (Survived). En otras palabras, es más probable que las personas que pagaron tarifas más altas tengan una mayor tasa de supervivencia.



#Por otro lado, si se observa una celda oscura cercana a -1 en la intersección de las variables 'Age' y 'Pclass', esto podría indicar una correlación negativa entre la edad (Age) y la clase de pasajero (Pclass). En este caso, podría significar que las personas en clases de pasajero más bajas tienden a ser más jóvenes.

# **DATASET WINE**



dataSetWine='wine.csv'
df_wine = pd.read_csv(dataSetWine)

print(df_wine.head())

print(df_wine.info())





#TIPOS DE VARIABLES

variablesWine = df_wine.columns.tolist()
print("Variables en el dataset:")
for variable in variablesWine:
    print(variable)

print('\n')

tipos_de_datos = df_wine.dtypes #tipo de dato
print("Tipos de Categorías de Variables:")
print(tipos_de_datos)

print('\n')

#Valores Ausente
valores_ausentes = df_wine.isnull().sum() #valores ausentes
print(valores_ausentes)
#Valor Atipico
df_wine.describe()


#En esta lista de Variables estan TODAS y su eexplicacion con referencia al
#dataset y el tipo de variable que seria

# Variables en el dataset y su explicación
variables_explicacion = {
    'fixed acidity': 'Acidez fija',
    'volatile acidity': 'Acidez volátil',
    'citric acid': 'Ácido cítrico',
    'residual sugar': 'Azúcar residual',
    'chlorides': 'Cloruros',
    'free sulfur dioxide': 'Dióxido de azufre libre',
    'total sulfur dioxide': 'Dióxido de azufre total',
    'density': 'Densidad',
    'pH': 'pH',
    'sulphates': 'Sulfatos',
    'alcohol': 'Alcohol',
    'quality': 'Calidad'
}

# Tipos de Categorías de Variables
categorias_variable = {
    'fixed acidity': 'Numérica (Continua)',
    'volatile acidity': 'Numérica (Continua)',
    'citric acid': 'Numérica (Continua)',
    'residual sugar': 'Numérica (Continua)',
    'chlorides': 'Numérica (Continua)',
    'free sulfur dioxide': 'Numérica (Continua)',
    'total sulfur dioxide': 'Numérica (Continua)',
    'density': 'Numérica (Continua)',
    'pH': 'Numérica (Continua)',
    'sulphates': 'Numérica (Continua)',
    'alcohol': 'Numérica (Continua)',
    'quality': 'Categórica (Ordinal)'
}

# Imprimir información de variables y categorías
for variable, explicacion in variables_explicacion.items():
    categoria = categorias_variable[variable]
    print(f'Variable: {variable}')
    print(f'Explicación: {explicacion}')
    print(f'Tipo de Variable: {categoria}')
    print('-----------------------------------')



#Elimino la columna chlorides
columna_eliminada = df_wine.drop(['OD'], axis=1)
print(columna_eliminada)

df_wine_quality = pd.read_csv('winequality-red.csv')

# Gráfico de Frecuencia para la columna "pH"
plt.figure(figsize=(8, 6))#tamaño
sns.countplot(x="pH", data=df_wine_quality)#histograma
plt.title("Gráfico de Frecuencia de pH")
plt.xlabel("PH")
plt.ylabel("Frecuencia")
plt.show()



# Grafico de torta"
plt.figure(figsize=(8, 6))
df_wine_quality["free sulfur dioxide"].value_counts().plot.pie(autopct="%1.1f%%")
plt.title("Gráfico de Torta de free sulfur dioxide")
plt.ylabel("Dioxido de sulfuro")
plt.show()


# Histograma para la Concentración de Alcohol
plt.figure(figsize=(8, 6))
plt.hist(df_wine_quality["alcohol"], bins=15, edgecolor="black")
plt.title("Histograma de Concentración de Alcohol")
plt.xlabel("Concentración de Alcohol")
plt.ylabel("Frecuencia")
plt.show()


#**En base a los graficos del punto 6 realizar distintas concluciones**

#*En el grafico de Torta se analiza el dioxido de azufre libre en los vinos,  la mayoría de las porciones son muy pequeñas, lo que indica que hay una variedad significativa en los niveles de dióxido de azufre libre en los vinos. Aunque esta varia entre unos y otros en su proporcion.

#*En el grafioc de frecuencia se muestra la distribucion de pH en cada clase de vino, estos estan distribuidas de manera uniforme y da como resultado un aplio rango lo que hace la diferencia en los vinos por su acidez.

#*En el ultimo grafico se observa que la mayor concentracion de alcohol en los vinos esta en 9 y 14, tambien hay una pequeña cantidad de vinos con una concentracion muy elevada (15) lo cual seria un valor atipico.


columnas_Wine = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']

correlation_matrix = df_wine_quality[columnas_Wine].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm")
plt.title("Matriz de Correlación")
plt.show()

# **ANALISIS DEL GRAFICO DE CORRELACION**

#En la matriz de correlación de los atributos de los vinos, podemos observar las relaciones entre las diferentes características químicas y de calidad de los vinos. Cada celda en la matriz representa la correlación entre dos atributos. Vamos a analizar algunas conclusiones a partir de este análisis:

#Acidez Fija y Acidez Volátil: Observamos una correlación positiva moderada entre "fixed acidity" (acidez fija) y "volatile acidity" (acidez volátil), lo que sugiere que los vinos con mayor acidez fija tienden a tener también una mayor acidez volátil. Esto podría deberse a que ambas medidas están relacionadas con la acidez general del vino.

#Ácido Cítrico y pH: Existe una correlación negativa débil entre "citric acid" (ácido cítrico) y "pH", lo que sugiere que los vinos con mayor contenido de ácido cítrico tienden a tener un pH ligeramente más bajo. El ácido cítrico puede influir en la acidez y el pH del vino.

#Azúcar Residual y Densidad: Hay una correlación positiva significativa entre "residual sugar" (azúcar residual) y "density" (densidad). Esto podría indicar que los vinos con mayor contenido de azúcar residual también tienen una mayor densidad.

#Dióxido de Azufre Libre y Dióxido de Azufre Total: Observamos una correlación positiva moderada entre "free sulfur dioxide" (dióxido de azufre libre) y "total sulfur dioxide" (dióxido de azufre total). Esto podría sugerir que estos dos componentes químicos están relacionados en la composición del vino.

#Sulfatos y Alcohol: Existe una correlación positiva débil entre "sulphates" (sulfatos) y "alcohol", indicando que los vinos con mayor contenido de sulfatos también tienden a tener un mayor contenido alcohólico.

#Calidad y Alcohol: Se observa una correlación positiva moderada entre "quality" (calidad) y "alcohol". Esto sugiere que los vinos con mayor contenido alcohólico tienden a tener una mayor calidad percibida.